# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'imgPlotUinoDock2.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QDoubleSpinBox,
    QGridLayout, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QSpacerItem, QSplitter, QStatusBar, QVBoxLayout,
    QWidget)

from pyqtgraph import GraphicsLayoutWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1753, 1454)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QSize(40, 0))
        self.label_3.setMaximumSize(QSize(40, 16777215))
        font = QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.label_3)

        self.doubleSpinBox_h11 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_h11.setObjectName(u"doubleSpinBox_h11")
        sizePolicy.setHeightForWidth(self.doubleSpinBox_h11.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_h11.setSizePolicy(sizePolicy)
        self.doubleSpinBox_h11.setMinimumSize(QSize(80, 0))
        self.doubleSpinBox_h11.setMaximumSize(QSize(50, 20))
        self.doubleSpinBox_h11.setFont(font)
        self.doubleSpinBox_h11.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.doubleSpinBox_h11.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox_h11.setDecimals(1)
        self.doubleSpinBox_h11.setMinimum(-10.000000000000000)
        self.doubleSpinBox_h11.setMaximum(10.000000000000000)
        self.doubleSpinBox_h11.setSingleStep(0.100000000000000)
        self.doubleSpinBox_h11.setStepType(QAbstractSpinBox.StepType.DefaultStepType)

        self.horizontalLayout.addWidget(self.doubleSpinBox_h11)

        self.doubleSpinBox_h12 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_h12.setObjectName(u"doubleSpinBox_h12")
        sizePolicy.setHeightForWidth(self.doubleSpinBox_h12.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_h12.setSizePolicy(sizePolicy)
        self.doubleSpinBox_h12.setMinimumSize(QSize(80, 0))
        self.doubleSpinBox_h12.setMaximumSize(QSize(50, 20))
        self.doubleSpinBox_h12.setFont(font)
        self.doubleSpinBox_h12.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.doubleSpinBox_h12.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox_h12.setDecimals(1)
        self.doubleSpinBox_h12.setMaximum(10.000000000000000)
        self.doubleSpinBox_h12.setSingleStep(0.100000000000000)

        self.horizontalLayout.addWidget(self.doubleSpinBox_h12)

        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(40, 0))
        self.label_2.setMaximumSize(QSize(50, 16777215))
        self.label_2.setFont(font)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.label_2)

        self.doubleSpinBox_v11 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_v11.setObjectName(u"doubleSpinBox_v11")
        sizePolicy.setHeightForWidth(self.doubleSpinBox_v11.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_v11.setSizePolicy(sizePolicy)
        self.doubleSpinBox_v11.setMinimumSize(QSize(80, 10))
        self.doubleSpinBox_v11.setMaximumSize(QSize(50, 20))
        self.doubleSpinBox_v11.setFont(font)
        self.doubleSpinBox_v11.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.doubleSpinBox_v11.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox_v11.setDecimals(1)
        self.doubleSpinBox_v11.setMinimum(-10.000000000000000)
        self.doubleSpinBox_v11.setMaximum(10.000000000000000)
        self.doubleSpinBox_v11.setSingleStep(0.100000000000000)

        self.horizontalLayout.addWidget(self.doubleSpinBox_v11)

        self.doubleSpinBox_v12 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_v12.setObjectName(u"doubleSpinBox_v12")
        sizePolicy.setHeightForWidth(self.doubleSpinBox_v12.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_v12.setSizePolicy(sizePolicy)
        self.doubleSpinBox_v12.setMinimumSize(QSize(80, 0))
        self.doubleSpinBox_v12.setMaximumSize(QSize(50, 20))
        self.doubleSpinBox_v12.setFont(font)
        self.doubleSpinBox_v12.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.doubleSpinBox_v12.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.doubleSpinBox_v12.setDecimals(1)
        self.doubleSpinBox_v12.setMaximum(10.000000000000000)
        self.doubleSpinBox_v12.setSingleStep(0.100000000000000)
        self.doubleSpinBox_v12.setStepType(QAbstractSpinBox.StepType.DefaultStepType)

        self.horizontalLayout.addWidget(self.doubleSpinBox_v12)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_4)


        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QSize(30, 0))
        self.label_9.setMaximumSize(QSize(30, 16777215))
        self.label_9.setFont(font)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_6.addWidget(self.label_9)

        self.label_Res1 = QLabel(self.centralwidget)
        self.label_Res1.setObjectName(u"label_Res1")
        sizePolicy.setHeightForWidth(self.label_Res1.sizePolicy().hasHeightForWidth())
        self.label_Res1.setSizePolicy(sizePolicy)
        self.label_Res1.setMinimumSize(QSize(40, 0))
        self.label_Res1.setMaximumSize(QSize(40, 16777215))
        font1 = QFont()
        font1.setPointSize(10)
        self.label_Res1.setFont(font1)
        self.label_Res1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_6.addWidget(self.label_Res1)


        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)

        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QSize(45, 0))
        self.label_8.setMaximumSize(QSize(45, 16777215))
        self.label_8.setFont(font)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_5.addWidget(self.label_8)

        self.lineEdit_n_max1 = QLineEdit(self.centralwidget)
        self.lineEdit_n_max1.setObjectName(u"lineEdit_n_max1")
        sizePolicy.setHeightForWidth(self.lineEdit_n_max1.sizePolicy().hasHeightForWidth())
        self.lineEdit_n_max1.setSizePolicy(sizePolicy)
        self.lineEdit_n_max1.setMinimumSize(QSize(60, 0))
        self.lineEdit_n_max1.setMaximumSize(QSize(30, 16777215))
        self.lineEdit_n_max1.setBaseSize(QSize(30, 0))
        self.lineEdit_n_max1.setFont(font)
        self.lineEdit_n_max1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_5.addWidget(self.lineEdit_n_max1)

        self.cmap1 = QComboBox(self.centralwidget)
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.addItem("")
        self.cmap1.setObjectName(u"cmap1")
        sizePolicy.setHeightForWidth(self.cmap1.sizePolicy().hasHeightForWidth())
        self.cmap1.setSizePolicy(sizePolicy)
        self.cmap1.setMinimumSize(QSize(120, 20))
        self.cmap1.setMaximumSize(QSize(80, 20))
        self.cmap1.setBaseSize(QSize(90, 0))
        self.cmap1.setFont(font)

        self.horizontalLayout_5.addWidget(self.cmap1)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_3)


        self.horizontalLayout_11.addLayout(self.horizontalLayout_5)


        self.verticalLayout_3.addLayout(self.horizontalLayout_11)

        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.layoutWidget = QWidget(self.splitter)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.graphicsLayoutWidget_gw1 = GraphicsLayoutWidget(self.layoutWidget)
        self.graphicsLayoutWidget_gw1.setObjectName(u"graphicsLayoutWidget_gw1")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.graphicsLayoutWidget_gw1.sizePolicy().hasHeightForWidth())
        self.graphicsLayoutWidget_gw1.setSizePolicy(sizePolicy1)
        self.graphicsLayoutWidget_gw1.setMinimumSize(QSize(300, 300))

        self.verticalLayout.addWidget(self.graphicsLayoutWidget_gw1)

        self.graphicsLayoutWidget_gw2 = GraphicsLayoutWidget(self.layoutWidget)
        self.graphicsLayoutWidget_gw2.setObjectName(u"graphicsLayoutWidget_gw2")
        sizePolicy1.setHeightForWidth(self.graphicsLayoutWidget_gw2.sizePolicy().hasHeightForWidth())
        self.graphicsLayoutWidget_gw2.setSizePolicy(sizePolicy1)
        self.graphicsLayoutWidget_gw2.setMinimumSize(QSize(300, 300))

        self.verticalLayout.addWidget(self.graphicsLayoutWidget_gw2)

        self.splitter.addWidget(self.layoutWidget)
        self.horizontalLayoutWidget = QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayout_10 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.graphicsLayoutWidget_gw3 = GraphicsLayoutWidget(self.horizontalLayoutWidget)
        self.graphicsLayoutWidget_gw3.setObjectName(u"graphicsLayoutWidget_gw3")
        sizePolicy1.setHeightForWidth(self.graphicsLayoutWidget_gw3.sizePolicy().hasHeightForWidth())
        self.graphicsLayoutWidget_gw3.setSizePolicy(sizePolicy1)
        self.graphicsLayoutWidget_gw3.setMinimumSize(QSize(600, 600))
        self.graphicsLayoutWidget_gw3.setSizeIncrement(QSize(0, 10))

        self.horizontalLayout_10.addWidget(self.graphicsLayoutWidget_gw3)

        self.splitter.addWidget(self.horizontalLayoutWidget)

        self.verticalLayout_3.addWidget(self.splitter)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy2)
        self.label.setFont(font)

        self.horizontalLayout_7.addWidget(self.label)

        self.label_h2x = QLabel(self.centralwidget)
        self.label_h2x.setObjectName(u"label_h2x")
        sizePolicy2.setHeightForWidth(self.label_h2x.sizePolicy().hasHeightForWidth())
        self.label_h2x.setSizePolicy(sizePolicy2)
        self.label_h2x.setMinimumSize(QSize(400, 0))

        self.horizontalLayout_7.addWidget(self.label_h2x)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        sizePolicy2.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy2)
        self.label_11.setFont(font)

        self.horizontalLayout_8.addWidget(self.label_11)

        self.label_h3x = QLabel(self.centralwidget)
        self.label_h3x.setObjectName(u"label_h3x")
        sizePolicy2.setHeightForWidth(self.label_h3x.sizePolicy().hasHeightForWidth())
        self.label_h3x.setSizePolicy(sizePolicy2)
        self.label_h3x.setMinimumSize(QSize(400, 0))

        self.horizontalLayout_8.addWidget(self.label_h3x)


        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_7.addItem(self.horizontalSpacer_5)


        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)


        self.verticalLayout_2.addLayout(self.horizontalLayout_9)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QSize(60, 0))
        self.label_7.setMaximumSize(QSize(45, 16777215))
        self.label_7.setFont(font)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.label_7)

        self.lineEdit_n_max2 = QLineEdit(self.centralwidget)
        self.lineEdit_n_max2.setObjectName(u"lineEdit_n_max2")
        sizePolicy.setHeightForWidth(self.lineEdit_n_max2.sizePolicy().hasHeightForWidth())
        self.lineEdit_n_max2.setSizePolicy(sizePolicy)
        self.lineEdit_n_max2.setMinimumSize(QSize(40, 0))
        self.lineEdit_n_max2.setMaximumSize(QSize(30, 16777215))
        self.lineEdit_n_max2.setBaseSize(QSize(30, 0))
        self.lineEdit_n_max2.setFont(font)
        self.lineEdit_n_max2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.lineEdit_n_max2)

        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QSize(60, 0))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.label_4)

        self.lineEdit_res2 = QLineEdit(self.centralwidget)
        self.lineEdit_res2.setObjectName(u"lineEdit_res2")
        sizePolicy.setHeightForWidth(self.lineEdit_res2.sizePolicy().hasHeightForWidth())
        self.lineEdit_res2.setSizePolicy(sizePolicy)
        self.lineEdit_res2.setMaximumSize(QSize(60, 16777215))
        self.lineEdit_res2.setFont(font)
        self.lineEdit_res2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.lineEdit_res2)

        self.cmap2 = QComboBox(self.centralwidget)
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.addItem("")
        self.cmap2.setObjectName(u"cmap2")
        sizePolicy.setHeightForWidth(self.cmap2.sizePolicy().hasHeightForWidth())
        self.cmap2.setSizePolicy(sizePolicy)
        self.cmap2.setMinimumSize(QSize(150, 20))
        self.cmap2.setMaximumSize(QSize(80, 20))
        self.cmap2.setBaseSize(QSize(90, 0))
        self.cmap2.setFont(font)

        self.horizontalLayout_2.addWidget(self.cmap2)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)


        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QSize(60, 0))
        self.label_6.setMaximumSize(QSize(45, 16777215))
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_6)

        self.lineEdit_n_max3 = QLineEdit(self.centralwidget)
        self.lineEdit_n_max3.setObjectName(u"lineEdit_n_max3")
        sizePolicy.setHeightForWidth(self.lineEdit_n_max3.sizePolicy().hasHeightForWidth())
        self.lineEdit_n_max3.setSizePolicy(sizePolicy)
        self.lineEdit_n_max3.setMinimumSize(QSize(40, 0))
        self.lineEdit_n_max3.setMaximumSize(QSize(30, 16777215))
        self.lineEdit_n_max3.setBaseSize(QSize(30, 0))
        self.lineEdit_n_max3.setFont(font)
        self.lineEdit_n_max3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.lineEdit_n_max3)

        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_5)

        self.lineEdit_res3 = QLineEdit(self.centralwidget)
        self.lineEdit_res3.setObjectName(u"lineEdit_res3")
        sizePolicy.setHeightForWidth(self.lineEdit_res3.sizePolicy().hasHeightForWidth())
        self.lineEdit_res3.setSizePolicy(sizePolicy)
        self.lineEdit_res3.setMaximumSize(QSize(60, 16777215))
        self.lineEdit_res3.setFont(font)
        self.lineEdit_res3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.lineEdit_res3)

        self.cmap3 = QComboBox(self.centralwidget)
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.addItem("")
        self.cmap3.setObjectName(u"cmap3")
        sizePolicy.setHeightForWidth(self.cmap3.sizePolicy().hasHeightForWidth())
        self.cmap3.setSizePolicy(sizePolicy)
        self.cmap3.setMinimumSize(QSize(150, 20))
        self.cmap3.setMaximumSize(QSize(80, 20))
        self.cmap3.setBaseSize(QSize(90, 0))
        self.cmap3.setFont(font)

        self.horizontalLayout_3.addWidget(self.cmap3)

        self.quitButton_2 = QPushButton(self.centralwidget)
        self.quitButton_2.setObjectName(u"quitButton_2")
        sizePolicy.setHeightForWidth(self.quitButton_2.sizePolicy().hasHeightForWidth())
        self.quitButton_2.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        self.quitButton_2.setFont(font2)

        self.horizontalLayout_3.addWidget(self.quitButton_2)


        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)


        self.verticalLayout_2.addLayout(self.horizontalLayout_4)


        self.verticalLayout_3.addLayout(self.verticalLayout_2)


        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1753, 62))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.quitButton_2.clicked["bool"].connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"H(Re) :", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"V(Im) :", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Res1:", None))
        self.label_Res1.setText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"n_max1", None))
        self.lineEdit_n_max1.setText("")
        self.cmap1.setItemText(0, QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.cmap1.setItemText(1, QCoreApplication.translate("MainWindow", u"CET_C5s", None))
        self.cmap1.setItemText(2, QCoreApplication.translate("MainWindow", u"CET_C1", None))
        self.cmap1.setItemText(3, QCoreApplication.translate("MainWindow", u"CET_C1s", None))
        self.cmap1.setItemText(4, QCoreApplication.translate("MainWindow", u"CET_C9", None))
        self.cmap1.setItemText(5, QCoreApplication.translate("MainWindow", u"CET_C9s", None))
        self.cmap1.setItemText(6, QCoreApplication.translate("MainWindow", u"CET_C2", None))
        self.cmap1.setItemText(7, QCoreApplication.translate("MainWindow", u"CET_C8", None))
        self.cmap1.setItemText(8, QCoreApplication.translate("MainWindow", u"CET_C8s", None))
        self.cmap1.setItemText(9, QCoreApplication.translate("MainWindow", u"CET_CBC1", None))
        self.cmap1.setItemText(10, QCoreApplication.translate("MainWindow", u"CET_CBC2", None))
        self.cmap1.setItemText(11, QCoreApplication.translate("MainWindow", u"CET_C6", None))
        self.cmap1.setItemText(12, QCoreApplication.translate("MainWindow", u"CET_C6s", None))
        self.cmap1.setItemText(13, QCoreApplication.translate("MainWindow", u"CET_CBTC1", None))
        self.cmap1.setItemText(14, QCoreApplication.translate("MainWindow", u"CET_CBTC2", None))
        self.cmap1.setItemText(15, QCoreApplication.translate("MainWindow", u"CET_C3", None))
        self.cmap1.setItemText(16, QCoreApplication.translate("MainWindow", u"CET_C3s", None))
        self.cmap1.setItemText(17, QCoreApplication.translate("MainWindow", u"CET_C4", None))
        self.cmap1.setItemText(18, QCoreApplication.translate("MainWindow", u"CET_C4s", None))
        self.cmap1.setItemText(19, QCoreApplication.translate("MainWindow", u"CET_C7", None))
        self.cmap1.setItemText(20, QCoreApplication.translate("MainWindow", u"CET_C7s", None))
        self.cmap1.setItemText(21, QCoreApplication.translate("MainWindow", u"CET_D4", None))
        self.cmap1.setItemText(22, QCoreApplication.translate("MainWindow", u"CET_D6", None))
        self.cmap1.setItemText(23, QCoreApplication.translate("MainWindow", u"CET_D13", None))
        self.cmap1.setItemText(24, QCoreApplication.translate("MainWindow", u"CET_D1A", None))
        self.cmap1.setItemText(25, QCoreApplication.translate("MainWindow", u"CET_D1", None))
        self.cmap1.setItemText(26, QCoreApplication.translate("MainWindow", u"CET_D9", None))
        self.cmap1.setItemText(27, QCoreApplication.translate("MainWindow", u"CET_D10", None))
        self.cmap1.setItemText(28, QCoreApplication.translate("MainWindow", u"diverging_gkr_60_10_c40", None))
        self.cmap1.setItemText(29, QCoreApplication.translate("MainWindow", u"CET_D3", None))
        self.cmap1.setItemText(30, QCoreApplication.translate("MainWindow", u"CET_D2", None))
        self.cmap1.setItemText(31, QCoreApplication.translate("MainWindow", u"CET_D12", None))
        self.cmap1.setItemText(32, QCoreApplication.translate("MainWindow", u"diverging_isoluminant_cjm_75_c24", None))
        self.cmap1.setItemText(33, QCoreApplication.translate("MainWindow", u"CET_D11", None))
        self.cmap1.setItemText(34, QCoreApplication.translate("MainWindow", u"CET_D8", None))
        self.cmap1.setItemText(35, QCoreApplication.translate("MainWindow", u"CET_D7", None))
        self.cmap1.setItemText(36, QCoreApplication.translate("MainWindow", u"CET_CBD2", None))
        self.cmap1.setItemText(37, QCoreApplication.translate("MainWindow", u"CET_CBD1", None))
        self.cmap1.setItemText(38, QCoreApplication.translate("MainWindow", u"CET_R3", None))
        self.cmap1.setItemText(39, QCoreApplication.translate("MainWindow", u"CET_CBTD1", None))
        self.cmap1.setItemText(40, QCoreApplication.translate("MainWindow", u"glasbey_bw", None))
        self.cmap1.setItemText(41, QCoreApplication.translate("MainWindow", u"glasbey", None))
        self.cmap1.setItemText(42, QCoreApplication.translate("MainWindow", u"glasbey_cool", None))
        self.cmap1.setItemText(43, QCoreApplication.translate("MainWindow", u"glasbey_dark", None))
        self.cmap1.setItemText(44, QCoreApplication.translate("MainWindow", u"glasbey_light", None))
        self.cmap1.setItemText(45, QCoreApplication.translate("MainWindow", u"glasbey_category10", None))
        self.cmap1.setItemText(46, QCoreApplication.translate("MainWindow", u"glasbey_hv", None))
        self.cmap1.setItemText(47, QCoreApplication.translate("MainWindow", u"CET_I1", None))
        self.cmap1.setItemText(48, QCoreApplication.translate("MainWindow", u"CET_I2", None))
        self.cmap1.setItemText(49, QCoreApplication.translate("MainWindow", u"CET_I3", None))
        self.cmap1.setItemText(50, QCoreApplication.translate("MainWindow", u"bgy", None))
        self.cmap1.setItemText(51, QCoreApplication.translate("MainWindow", u"linear_bgyw_15_100_c67", None))
        self.cmap1.setItemText(52, QCoreApplication.translate("MainWindow", u"bgyw", None))
        self.cmap1.setItemText(53, QCoreApplication.translate("MainWindow", u"CET_L9", None))
        self.cmap1.setItemText(54, QCoreApplication.translate("MainWindow", u"CET_L12", None))
        self.cmap1.setItemText(55, QCoreApplication.translate("MainWindow", u"CET_L7", None))
        self.cmap1.setItemText(56, QCoreApplication.translate("MainWindow", u"bmw", None))
        self.cmap1.setItemText(57, QCoreApplication.translate("MainWindow", u"CET_L8", None))
        self.cmap1.setItemText(58, QCoreApplication.translate("MainWindow", u"bmy", None))
        self.cmap1.setItemText(59, QCoreApplication.translate("MainWindow", u"CET_L10", None))
        self.cmap1.setItemText(60, QCoreApplication.translate("MainWindow", u"CET_L11", None))
        self.cmap1.setItemText(61, QCoreApplication.translate("MainWindow", u"CET_L1", None))
        self.cmap1.setItemText(62, QCoreApplication.translate("MainWindow", u"CET_L2", None))
        self.cmap1.setItemText(63, QCoreApplication.translate("MainWindow", u"CET_L6", None))
        self.cmap1.setItemText(64, QCoreApplication.translate("MainWindow", u"CET_L20", None))
        self.cmap1.setItemText(65, QCoreApplication.translate("MainWindow", u"kbgyw", None))
        self.cmap1.setItemText(66, QCoreApplication.translate("MainWindow", u"CET_L16", None))
        self.cmap1.setItemText(67, QCoreApplication.translate("MainWindow", u"CET_L5", None))
        self.cmap1.setItemText(68, QCoreApplication.translate("MainWindow", u"CET_L4", None))
        self.cmap1.setItemText(69, QCoreApplication.translate("MainWindow", u"linear_kry_5_95_c72", None))
        self.cmap1.setItemText(70, QCoreApplication.translate("MainWindow", u"linear_kry_5_98_c75", None))
        self.cmap1.setItemText(71, QCoreApplication.translate("MainWindow", u"CET_L3", None))
        self.cmap1.setItemText(72, QCoreApplication.translate("MainWindow", u"linear_kryw_0_100_c64", None))
        self.cmap1.setItemText(73, QCoreApplication.translate("MainWindow", u"linear_kryw_0_100_c67", None))
        self.cmap1.setItemText(74, QCoreApplication.translate("MainWindow", u"CET_CBL1", None))
        self.cmap1.setItemText(75, QCoreApplication.translate("MainWindow", u"CET_CBL3", None))
        self.cmap1.setItemText(76, QCoreApplication.translate("MainWindow", u"CET_CBL2", None))
        self.cmap1.setItemText(77, QCoreApplication.translate("MainWindow", u"CET_CBL4", None))
        self.cmap1.setItemText(78, QCoreApplication.translate("MainWindow", u"CET_L15", None))
        self.cmap1.setItemText(79, QCoreApplication.translate("MainWindow", u"CET_L14", None))
        self.cmap1.setItemText(80, QCoreApplication.translate("MainWindow", u"CET_L13", None))
        self.cmap1.setItemText(81, QCoreApplication.translate("MainWindow", u"CET_CBTL3", None))
        self.cmap1.setItemText(82, QCoreApplication.translate("MainWindow", u"CET_CBTL2", None))
        self.cmap1.setItemText(83, QCoreApplication.translate("MainWindow", u"CET_CBTL1", None))
        self.cmap1.setItemText(84, QCoreApplication.translate("MainWindow", u"CET_CBTL4", None))
        self.cmap1.setItemText(85, QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.cmap1.setItemText(86, QCoreApplication.translate("MainWindow", u"CET_L17", None))
        self.cmap1.setItemText(87, QCoreApplication.translate("MainWindow", u"CET_L18", None))
        self.cmap1.setItemText(88, QCoreApplication.translate("MainWindow", u"CET_R4", None))
        self.cmap1.setItemText(89, QCoreApplication.translate("MainWindow", u"CET_R2", None))
        self.cmap1.setItemText(90, QCoreApplication.translate("MainWindow", u"rainbow", None))
        self.cmap1.setItemText(91, QCoreApplication.translate("MainWindow", u"CET_R1", None))
        self.cmap1.setItemText(92, QCoreApplication.translate("MainWindow", u"rainbow_bgyrm_35_85_c71", None))

        self.cmap1.setCurrentText(QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"h2x, v2x:", None))
        self.label_h2x.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"h3x, v3x:", None))
        self.label_h3x.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"n_max2", None))
        self.lineEdit_n_max2.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Res2:", None))
        self.lineEdit_res2.setText("")
        self.cmap2.setItemText(0, QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.cmap2.setItemText(1, QCoreApplication.translate("MainWindow", u"CET_C5s", None))
        self.cmap2.setItemText(2, QCoreApplication.translate("MainWindow", u"CET_C1", None))
        self.cmap2.setItemText(3, QCoreApplication.translate("MainWindow", u"CET_C1s", None))
        self.cmap2.setItemText(4, QCoreApplication.translate("MainWindow", u"CET_C9", None))
        self.cmap2.setItemText(5, QCoreApplication.translate("MainWindow", u"CET_C9s", None))
        self.cmap2.setItemText(6, QCoreApplication.translate("MainWindow", u"CET_C2", None))
        self.cmap2.setItemText(7, QCoreApplication.translate("MainWindow", u"CET_C8", None))
        self.cmap2.setItemText(8, QCoreApplication.translate("MainWindow", u"CET_C8s", None))
        self.cmap2.setItemText(9, QCoreApplication.translate("MainWindow", u"CET_CBC1", None))
        self.cmap2.setItemText(10, QCoreApplication.translate("MainWindow", u"CET_CBC2", None))
        self.cmap2.setItemText(11, QCoreApplication.translate("MainWindow", u"CET_C6", None))
        self.cmap2.setItemText(12, QCoreApplication.translate("MainWindow", u"CET_C6s", None))
        self.cmap2.setItemText(13, QCoreApplication.translate("MainWindow", u"CET_CBTC1", None))
        self.cmap2.setItemText(14, QCoreApplication.translate("MainWindow", u"CET_CBTC2", None))
        self.cmap2.setItemText(15, QCoreApplication.translate("MainWindow", u"CET_C3", None))
        self.cmap2.setItemText(16, QCoreApplication.translate("MainWindow", u"CET_C3s", None))
        self.cmap2.setItemText(17, QCoreApplication.translate("MainWindow", u"CET_C4", None))
        self.cmap2.setItemText(18, QCoreApplication.translate("MainWindow", u"CET_C4s", None))
        self.cmap2.setItemText(19, QCoreApplication.translate("MainWindow", u"CET_C7", None))
        self.cmap2.setItemText(20, QCoreApplication.translate("MainWindow", u"CET_C7s", None))
        self.cmap2.setItemText(21, QCoreApplication.translate("MainWindow", u"CET_D4", None))
        self.cmap2.setItemText(22, QCoreApplication.translate("MainWindow", u"CET_D6", None))
        self.cmap2.setItemText(23, QCoreApplication.translate("MainWindow", u"CET_D13", None))
        self.cmap2.setItemText(24, QCoreApplication.translate("MainWindow", u"CET_D1A", None))
        self.cmap2.setItemText(25, QCoreApplication.translate("MainWindow", u"CET_D1", None))
        self.cmap2.setItemText(26, QCoreApplication.translate("MainWindow", u"CET_D9", None))
        self.cmap2.setItemText(27, QCoreApplication.translate("MainWindow", u"CET_D10", None))
        self.cmap2.setItemText(28, QCoreApplication.translate("MainWindow", u"diverging_gkr_60_10_c40", None))
        self.cmap2.setItemText(29, QCoreApplication.translate("MainWindow", u"CET_D3", None))
        self.cmap2.setItemText(30, QCoreApplication.translate("MainWindow", u"CET_D2", None))
        self.cmap2.setItemText(31, QCoreApplication.translate("MainWindow", u"CET_D12", None))
        self.cmap2.setItemText(32, QCoreApplication.translate("MainWindow", u"diverging_isoluminant_cjm_75_c24", None))
        self.cmap2.setItemText(33, QCoreApplication.translate("MainWindow", u"CET_D11", None))
        self.cmap2.setItemText(34, QCoreApplication.translate("MainWindow", u"CET_D8", None))
        self.cmap2.setItemText(35, QCoreApplication.translate("MainWindow", u"CET_D7", None))
        self.cmap2.setItemText(36, QCoreApplication.translate("MainWindow", u"CET_CBD2", None))
        self.cmap2.setItemText(37, QCoreApplication.translate("MainWindow", u"CET_CBD1", None))
        self.cmap2.setItemText(38, QCoreApplication.translate("MainWindow", u"CET_R3", None))
        self.cmap2.setItemText(39, QCoreApplication.translate("MainWindow", u"CET_CBTD1", None))
        self.cmap2.setItemText(40, QCoreApplication.translate("MainWindow", u"glasbey_bw", None))
        self.cmap2.setItemText(41, QCoreApplication.translate("MainWindow", u"glasbey", None))
        self.cmap2.setItemText(42, QCoreApplication.translate("MainWindow", u"glasbey_cool", None))
        self.cmap2.setItemText(43, QCoreApplication.translate("MainWindow", u"glasbey_dark", None))
        self.cmap2.setItemText(44, QCoreApplication.translate("MainWindow", u"glasbey_light", None))
        self.cmap2.setItemText(45, QCoreApplication.translate("MainWindow", u"glasbey_category10", None))
        self.cmap2.setItemText(46, QCoreApplication.translate("MainWindow", u"glasbey_hv", None))
        self.cmap2.setItemText(47, QCoreApplication.translate("MainWindow", u"CET_I1", None))
        self.cmap2.setItemText(48, QCoreApplication.translate("MainWindow", u"CET_I2", None))
        self.cmap2.setItemText(49, QCoreApplication.translate("MainWindow", u"CET_I3", None))
        self.cmap2.setItemText(50, QCoreApplication.translate("MainWindow", u"bgy", None))
        self.cmap2.setItemText(51, QCoreApplication.translate("MainWindow", u"linear_bgyw_15_100_c67", None))
        self.cmap2.setItemText(52, QCoreApplication.translate("MainWindow", u"bgyw", None))
        self.cmap2.setItemText(53, QCoreApplication.translate("MainWindow", u"CET_L9", None))
        self.cmap2.setItemText(54, QCoreApplication.translate("MainWindow", u"CET_L12", None))
        self.cmap2.setItemText(55, QCoreApplication.translate("MainWindow", u"CET_L7", None))
        self.cmap2.setItemText(56, QCoreApplication.translate("MainWindow", u"bmw", None))
        self.cmap2.setItemText(57, QCoreApplication.translate("MainWindow", u"CET_L8", None))
        self.cmap2.setItemText(58, QCoreApplication.translate("MainWindow", u"bmy", None))
        self.cmap2.setItemText(59, QCoreApplication.translate("MainWindow", u"CET_L10", None))
        self.cmap2.setItemText(60, QCoreApplication.translate("MainWindow", u"CET_L11", None))
        self.cmap2.setItemText(61, QCoreApplication.translate("MainWindow", u"CET_L1", None))
        self.cmap2.setItemText(62, QCoreApplication.translate("MainWindow", u"CET_L2", None))
        self.cmap2.setItemText(63, QCoreApplication.translate("MainWindow", u"CET_L6", None))
        self.cmap2.setItemText(64, QCoreApplication.translate("MainWindow", u"CET_L20", None))
        self.cmap2.setItemText(65, QCoreApplication.translate("MainWindow", u"kbgyw", None))
        self.cmap2.setItemText(66, QCoreApplication.translate("MainWindow", u"CET_L16", None))
        self.cmap2.setItemText(67, QCoreApplication.translate("MainWindow", u"CET_L5", None))
        self.cmap2.setItemText(68, QCoreApplication.translate("MainWindow", u"CET_L4", None))
        self.cmap2.setItemText(69, QCoreApplication.translate("MainWindow", u"linear_kry_5_95_c72", None))
        self.cmap2.setItemText(70, QCoreApplication.translate("MainWindow", u"linear_kry_5_98_c75", None))
        self.cmap2.setItemText(71, QCoreApplication.translate("MainWindow", u"CET_L3", None))
        self.cmap2.setItemText(72, QCoreApplication.translate("MainWindow", u"linear_kryw_0_100_c64", None))
        self.cmap2.setItemText(73, QCoreApplication.translate("MainWindow", u"linear_kryw_0_100_c67", None))
        self.cmap2.setItemText(74, QCoreApplication.translate("MainWindow", u"CET_CBL1", None))
        self.cmap2.setItemText(75, QCoreApplication.translate("MainWindow", u"CET_CBL3", None))
        self.cmap2.setItemText(76, QCoreApplication.translate("MainWindow", u"CET_CBL2", None))
        self.cmap2.setItemText(77, QCoreApplication.translate("MainWindow", u"CET_CBL4", None))
        self.cmap2.setItemText(78, QCoreApplication.translate("MainWindow", u"CET_L15", None))
        self.cmap2.setItemText(79, QCoreApplication.translate("MainWindow", u"CET_L14", None))
        self.cmap2.setItemText(80, QCoreApplication.translate("MainWindow", u"CET_L13", None))
        self.cmap2.setItemText(81, QCoreApplication.translate("MainWindow", u"CET_CBTL3", None))
        self.cmap2.setItemText(82, QCoreApplication.translate("MainWindow", u"CET_CBTL2", None))
        self.cmap2.setItemText(83, QCoreApplication.translate("MainWindow", u"CET_CBTL1", None))
        self.cmap2.setItemText(84, QCoreApplication.translate("MainWindow", u"CET_CBTL4", None))
        self.cmap2.setItemText(85, QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.cmap2.setItemText(86, QCoreApplication.translate("MainWindow", u"CET_L17", None))
        self.cmap2.setItemText(87, QCoreApplication.translate("MainWindow", u"CET_L18", None))
        self.cmap2.setItemText(88, QCoreApplication.translate("MainWindow", u"CET_R4", None))
        self.cmap2.setItemText(89, QCoreApplication.translate("MainWindow", u"CET_R2", None))
        self.cmap2.setItemText(90, QCoreApplication.translate("MainWindow", u"rainbow", None))
        self.cmap2.setItemText(91, QCoreApplication.translate("MainWindow", u"CET_R1", None))
        self.cmap2.setItemText(92, QCoreApplication.translate("MainWindow", u"rainbow_bgyrm_35_85_c71", None))

        self.cmap2.setCurrentText(QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"n_max3", None))
        self.lineEdit_n_max3.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Res3:", None))
        self.lineEdit_res3.setText("")
        self.cmap3.setItemText(0, QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.cmap3.setItemText(1, QCoreApplication.translate("MainWindow", u"CET_C5s", None))
        self.cmap3.setItemText(2, QCoreApplication.translate("MainWindow", u"CET_C1", None))
        self.cmap3.setItemText(3, QCoreApplication.translate("MainWindow", u"CET_C1s", None))
        self.cmap3.setItemText(4, QCoreApplication.translate("MainWindow", u"CET_C9", None))
        self.cmap3.setItemText(5, QCoreApplication.translate("MainWindow", u"CET_C9s", None))
        self.cmap3.setItemText(6, QCoreApplication.translate("MainWindow", u"CET_C2", None))
        self.cmap3.setItemText(7, QCoreApplication.translate("MainWindow", u"CET_C8", None))
        self.cmap3.setItemText(8, QCoreApplication.translate("MainWindow", u"CET_C8s", None))
        self.cmap3.setItemText(9, QCoreApplication.translate("MainWindow", u"CET_CBC1", None))
        self.cmap3.setItemText(10, QCoreApplication.translate("MainWindow", u"CET_CBC2", None))
        self.cmap3.setItemText(11, QCoreApplication.translate("MainWindow", u"CET_C6", None))
        self.cmap3.setItemText(12, QCoreApplication.translate("MainWindow", u"CET_C6s", None))
        self.cmap3.setItemText(13, QCoreApplication.translate("MainWindow", u"CET_CBTC1", None))
        self.cmap3.setItemText(14, QCoreApplication.translate("MainWindow", u"CET_CBTC2", None))
        self.cmap3.setItemText(15, QCoreApplication.translate("MainWindow", u"CET_C3", None))
        self.cmap3.setItemText(16, QCoreApplication.translate("MainWindow", u"CET_C3s", None))
        self.cmap3.setItemText(17, QCoreApplication.translate("MainWindow", u"CET_C4", None))
        self.cmap3.setItemText(18, QCoreApplication.translate("MainWindow", u"CET_C4s", None))
        self.cmap3.setItemText(19, QCoreApplication.translate("MainWindow", u"CET_C7", None))
        self.cmap3.setItemText(20, QCoreApplication.translate("MainWindow", u"CET_C7s", None))
        self.cmap3.setItemText(21, QCoreApplication.translate("MainWindow", u"CET_D4", None))
        self.cmap3.setItemText(22, QCoreApplication.translate("MainWindow", u"CET_D6", None))
        self.cmap3.setItemText(23, QCoreApplication.translate("MainWindow", u"CET_D13", None))
        self.cmap3.setItemText(24, QCoreApplication.translate("MainWindow", u"CET_D1A", None))
        self.cmap3.setItemText(25, QCoreApplication.translate("MainWindow", u"CET_D1", None))
        self.cmap3.setItemText(26, QCoreApplication.translate("MainWindow", u"CET_D9", None))
        self.cmap3.setItemText(27, QCoreApplication.translate("MainWindow", u"CET_D10", None))
        self.cmap3.setItemText(28, QCoreApplication.translate("MainWindow", u"diverging_gkr_60_10_c40", None))
        self.cmap3.setItemText(29, QCoreApplication.translate("MainWindow", u"CET_D3", None))
        self.cmap3.setItemText(30, QCoreApplication.translate("MainWindow", u"CET_D2", None))
        self.cmap3.setItemText(31, QCoreApplication.translate("MainWindow", u"CET_D12", None))
        self.cmap3.setItemText(32, QCoreApplication.translate("MainWindow", u"diverging_isoluminant_cjm_75_c24", None))
        self.cmap3.setItemText(33, QCoreApplication.translate("MainWindow", u"CET_D11", None))
        self.cmap3.setItemText(34, QCoreApplication.translate("MainWindow", u"CET_D8", None))
        self.cmap3.setItemText(35, QCoreApplication.translate("MainWindow", u"CET_D7", None))
        self.cmap3.setItemText(36, QCoreApplication.translate("MainWindow", u"CET_CBD2", None))
        self.cmap3.setItemText(37, QCoreApplication.translate("MainWindow", u"CET_CBD1", None))
        self.cmap3.setItemText(38, QCoreApplication.translate("MainWindow", u"CET_R3", None))
        self.cmap3.setItemText(39, QCoreApplication.translate("MainWindow", u"CET_CBTD1", None))
        self.cmap3.setItemText(40, QCoreApplication.translate("MainWindow", u"glasbey_bw", None))
        self.cmap3.setItemText(41, QCoreApplication.translate("MainWindow", u"glasbey", None))
        self.cmap3.setItemText(42, QCoreApplication.translate("MainWindow", u"glasbey_cool", None))
        self.cmap3.setItemText(43, QCoreApplication.translate("MainWindow", u"glasbey_dark", None))
        self.cmap3.setItemText(44, QCoreApplication.translate("MainWindow", u"glasbey_light", None))
        self.cmap3.setItemText(45, QCoreApplication.translate("MainWindow", u"glasbey_category10", None))
        self.cmap3.setItemText(46, QCoreApplication.translate("MainWindow", u"glasbey_hv", None))
        self.cmap3.setItemText(47, QCoreApplication.translate("MainWindow", u"CET_I1", None))
        self.cmap3.setItemText(48, QCoreApplication.translate("MainWindow", u"CET_I2", None))
        self.cmap3.setItemText(49, QCoreApplication.translate("MainWindow", u"CET_I3", None))
        self.cmap3.setItemText(50, QCoreApplication.translate("MainWindow", u"bgy", None))
        self.cmap3.setItemText(51, QCoreApplication.translate("MainWindow", u"linear_bgyw_15_100_c67", None))
        self.cmap3.setItemText(52, QCoreApplication.translate("MainWindow", u"bgyw", None))
        self.cmap3.setItemText(53, QCoreApplication.translate("MainWindow", u"CET_L9", None))
        self.cmap3.setItemText(54, QCoreApplication.translate("MainWindow", u"CET_L12", None))
        self.cmap3.setItemText(55, QCoreApplication.translate("MainWindow", u"CET_L7", None))
        self.cmap3.setItemText(56, QCoreApplication.translate("MainWindow", u"bmw", None))
        self.cmap3.setItemText(57, QCoreApplication.translate("MainWindow", u"CET_L8", None))
        self.cmap3.setItemText(58, QCoreApplication.translate("MainWindow", u"bmy", None))
        self.cmap3.setItemText(59, QCoreApplication.translate("MainWindow", u"CET_L10", None))
        self.cmap3.setItemText(60, QCoreApplication.translate("MainWindow", u"CET_L11", None))
        self.cmap3.setItemText(61, QCoreApplication.translate("MainWindow", u"CET_L1", None))
        self.cmap3.setItemText(62, QCoreApplication.translate("MainWindow", u"CET_L2", None))
        self.cmap3.setItemText(63, QCoreApplication.translate("MainWindow", u"CET_L6", None))
        self.cmap3.setItemText(64, QCoreApplication.translate("MainWindow", u"CET_L20", None))
        self.cmap3.setItemText(65, QCoreApplication.translate("MainWindow", u"kbgyw", None))
        self.cmap3.setItemText(66, QCoreApplication.translate("MainWindow", u"CET_L16", None))
        self.cmap3.setItemText(67, QCoreApplication.translate("MainWindow", u"CET_L5", None))
        self.cmap3.setItemText(68, QCoreApplication.translate("MainWindow", u"CET_L4", None))
        self.cmap3.setItemText(69, QCoreApplication.translate("MainWindow", u"linear_kry_5_95_c72", None))
        self.cmap3.setItemText(70, QCoreApplication.translate("MainWindow", u"linear_kry_5_98_c75", None))
        self.cmap3.setItemText(71, QCoreApplication.translate("MainWindow", u"CET_L3", None))
        self.cmap3.setItemText(72, QCoreApplication.translate("MainWindow", u"linear_kryw_0_100_c64", None))
        self.cmap3.setItemText(73, QCoreApplication.translate("MainWindow", u"linear_kryw_0_100_c67", None))
        self.cmap3.setItemText(74, QCoreApplication.translate("MainWindow", u"CET_CBL1", None))
        self.cmap3.setItemText(75, QCoreApplication.translate("MainWindow", u"CET_CBL3", None))
        self.cmap3.setItemText(76, QCoreApplication.translate("MainWindow", u"CET_CBL2", None))
        self.cmap3.setItemText(77, QCoreApplication.translate("MainWindow", u"CET_CBL4", None))
        self.cmap3.setItemText(78, QCoreApplication.translate("MainWindow", u"CET_L15", None))
        self.cmap3.setItemText(79, QCoreApplication.translate("MainWindow", u"CET_L14", None))
        self.cmap3.setItemText(80, QCoreApplication.translate("MainWindow", u"CET_L13", None))
        self.cmap3.setItemText(81, QCoreApplication.translate("MainWindow", u"CET_CBTL3", None))
        self.cmap3.setItemText(82, QCoreApplication.translate("MainWindow", u"CET_CBTL2", None))
        self.cmap3.setItemText(83, QCoreApplication.translate("MainWindow", u"CET_CBTL1", None))
        self.cmap3.setItemText(84, QCoreApplication.translate("MainWindow", u"CET_CBTL4", None))
        self.cmap3.setItemText(85, QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.cmap3.setItemText(86, QCoreApplication.translate("MainWindow", u"CET_L17", None))
        self.cmap3.setItemText(87, QCoreApplication.translate("MainWindow", u"CET_L18", None))
        self.cmap3.setItemText(88, QCoreApplication.translate("MainWindow", u"CET_R4", None))
        self.cmap3.setItemText(89, QCoreApplication.translate("MainWindow", u"CET_R2", None))
        self.cmap3.setItemText(90, QCoreApplication.translate("MainWindow", u"rainbow", None))
        self.cmap3.setItemText(91, QCoreApplication.translate("MainWindow", u"CET_R1", None))
        self.cmap3.setItemText(92, QCoreApplication.translate("MainWindow", u"rainbow_bgyrm_35_85_c71", None))

        self.cmap3.setCurrentText(QCoreApplication.translate("MainWindow", u"CET_L19", None))
        self.quitButton_2.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
    # retranslateUi

